# Generated by Django 5.2.5 on 2025-08-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('ACT', 'Action'), ('COM', 'Comedy'), ('DRM', 'Drama'), ('HOR', 'Horror'), ('SCI', 'Sci‑Fi'), ('ANI', 'Animation'), ('DOC', 'Documentary'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('watched', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
